#+TITLE: 使用 Pentadactyl (Firefox add-on)
#+DATE: 2013-08-17
#+SETUPFILE: ~/.emacs.d/misc/org-mode/setupfile-sample.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: firefox
#+JEKYLL_PUBLISHED: true
#+JEKYLL_COMMENTS: true

#+BEGIN_QUOTE
Pentadactyl is a free browser add-on for Firefox, designed to make browsing more
efficient and especially more keyboard accessible.
#+END_QUOTE
[[http://5digits.org/pentadactyl/index][Pentadactyl]] 是一個能讓你快速瀏覽網頁的一個火狐插件，其特點是用 Vim-like 的方式來
使用，也可以是說是以鍵盤來做瀏覽動作的一套按法。
* 一些使用心得
{{{more}}}
先聲明有些是定制後的 Pentadactyl 才有的，所以預設的行為會和以下有些出入，還有我的
鍵盤的敏感度也調高了。

** 快速移動
按鍵 =j k= 分別為上下移動網頁約5%， =h l= 為切換瀏覽至左和右邊的 Tab =space= 為向
下一個 page ，加前綴 shift 為上。僅僅這些基礎移動就大大超越還在用和滑鼠點擊分頁的我了！
但失去滑鼠滾輪還是有差別的，所以我的使用習慣變為 =space= 在網頁上下移動後，之後使
用 =j k= 微調一下。 =gg= 和 =G= 為頁首和尾。還有 Mark 頁面的功能呢！
** 如何點超連結？
這有點說不清，實際用的情況是 =f= 後連結上頭會跑出英文字母，之後在照順序輸入你眼睛
盯著的連結上的英文字母， =F= 則是會開新分頁，是一個很實用的功能，我把連結上頭出現
的東西改成以 =asdfjkl;= 排，這樣八個鍵，連移動手指頭都不需要！
** 開啟網頁
=o= 在當前頁面開啟網頁， =t= 為開在新分頁，開啟後鍵入關鍵字，預設會使用 Google 搜
尋，有個很棒的功能叫 Auto-Completion ，使用時會根據關鍵字給予補全，這類似你在
Google 的搜尋欄鍵入關鍵字時會從下方跑出一個列表供你選擇，常用補全的東西有歷史紀錄
和剛剛提到搜尋引擎的補全，更多其他補全我也還不清楚但已經很夠用了。

例如輸入個巴會出現我最近看到的和巴哈姆特 有關聯的網址和 title 但卻還跑出和巴士海
峽相關的東西，當然能允許你更精確列出來，接個空白鍵和 gamer 或哈，就會產生更加有關
聯的資訊了。
** 其他實用的功能
=r= 為更新網頁、 =d= 為刪除 、 =b= 則是變成文字輸出你的分頁後選擇， =數字+b= 則是
直接跳轉至指定Tab， =/= 是搜尋當前頁面， =u= 回復剛關閉的頁面也能補全最近關過的頁
面， =Esc= 取消，其他的上官網看吧。
* 一個小短片
兩分鐘的影片

[[http://youtu.be/BuANeWJR-lM][Pentadactyl show on youtube]]
